################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: Network Tokens
  productionDescription: <p align="justify"> Network Tokens, also known as EMVCo payment tokens, are provided by the Card Networks in lieu of the cardholder’s PAN for use in Card Not Present (CNP) transactions only. Merchant Network Tokens are provisioned for use in Credential-On-File (COF) payments and are distinct for every customer-merchant pairing. </br></br> Fiserv Network Tokens direct APIs allows the merchant the ability to provision tokens outside of the transaction flow and also request cryptogram to use in consumer-initiated transactions agnostic of the processor. By leveraging easy to use APIs, merchant can display card art within their digital wallet or mobile application, receive lifecycle updates thereby enhancing the customer experience and satisfaction.</p>
  whoIsItFor: Netwrok Tokens provides better Auth/Sale transaction compared to traditioanl PAN based transaction and provdes ehnanced security overall.
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: Fiserv™
getStarted: /docs/getting-started.md
benefits:
  - title: Uplift authorization
    description: Dynamically updated network tokens help merchants realize an average 3% authorization uptick due to prevention of lifecycle declines on CNP transactions.
  - title: Enhanced security
    description: Issuers perform Fraud Screening during provisioning, allowing for continued use of the Network Token after the underlying PAN is suspended.
  - title: interchange savings
    description: Using network tokens can offer cost savings. Visa offers incentive rates for certain CNP consumer transactions that process with network tokens.
featuredFeatures:
  - title: On-the-Go
    description: No code option- enable Network Tokens on MIDs PAN or TransArmorToken can be sent for authorization. Fiserv will provision Network Token and use when available for authorization. Fiserv managed Network Token vault.
    tags: ["aSynchTokenization", "Tokenization", "Lifecycle", "Cryptogram"]
    bullets: ["aSynchTokenization", "Tokenization" , "Lifecycle", "Cryptogram"]
    relatedDocs:
      - relatedDoc: 
        title: Tokenization Introduction
        description: This API is to queue a provision token request for a PAN. It's asynch way of tokenization the PAN through different networks like VISA, MASTERCARD, DISCOVER, AMEX.
        link: /docs/interactive-guide/description.md
  - title: Digital Wallet
    description: Available through API calls and LCM push updates. Enhance digital wallets with card art. Ensure payment credentials are always current using LCM. Automatically detect outdated cards and seamlessly switch to Network tokens for authorization
  - title: Direct APIs
    description: Allow for provisioning, cryptograms, and updated Network Token data to be obtain outside of the authorization. Support processor-agnostic transactions using Network Tokens. Implement a merchant managed Network Token vault
