################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: Network Tokens
  productionDescription: Network Tokens services are provided by the Card Networks in lieu of the cardholder’s PAN, Also known as EMVCo Tokens or Payment Tokens.Network Tokens move through the payment networks in the same way as a PAN, allowing transactions to occur without the merchant being exposed to the underlying PAN. It can be used for credential on file payments (CNP)
  whoIsItFor: Netwrok Tokens provides better Auth/Sale transaction compared to traditioanl PAN based transaction and provdes ehnanced security overall.
  image: 
    link: "/assets/images/Fiserv_Logo.jpg"
    altText: REPLACEME™
getStarted: /docs/getting-started.md
featuredFeatures:
  - title: Network Tokens
    description:  Network Tokens Services for COF tokenization.
    tags: ["aSynchTokenization", "Tokenization", "Lifecycle", "Cryptogram"]
    bullets: ["aSynchTokenization", "Tokenization" , "Lifecycle", "Cryptogram"]
    relatedDocs:
      - relatedDoc: 
        title: aSynchTokenization
        description: This API is to queue a provision token request for a PAN. It's asynch way of tokenization the PAN through different networks like VISA, MASTERCARD, DISCOVER, AMEX.
        link: ./docs/asynchTokenization.md
      - relatedDoc: 
        title: Tokenization
        description: This API is to tokenize/provision a PAN data with issuer through different network engines like VISA, MASTERCARD, DISCOVER, AMEX.
        link: ./docs/synchTokenization.md
      - relatedDoc: 
        title: Lifecycle
        description: This API is to temporarily chnage the status of the token -  ACTIVE, SUSPEND, UNSUSPEND, DELETE are the lifecycle status.
        link: ./docs/merchantlcm.md
      - relatedDoc:
        title: Cryptogram
        description: This API is to create a Digital Secure Remote Payment transaction cryptogram using the credentials stored within netwrok to perfoem transaction.
        link: ./docs/cryptogram.md
