openapi: 3.0.3
info: { title: API Explorer, description: This Specification document lists the APIs required for provision a token for a PAN getting Cryptogram for a token and Lifecycle management for the provisioned token., version: 1.0.0 }
servers:
  - { url: 'https://api.fiservapps.com', description: Production }
  - { url: 'https:// cert.api.fiservapps.com', description: Cert Sandbox }
  - { url: 'https:// qa.api.fiservapps.com', description: QA Sandbox }
paths:
  /v1/test:
    x-model-version: 1.0
    post:
      tags: [ AsynchronousTest Tokenization API ]
      x-group-name: Tokenization
      x-proxy-name: CreateAsynchTokenTest
      summary: aSynchronous a provision token request.
      description: This API will provision token for a PAN Asynchronously with Network Services.
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/ProvisionTokenRequest1' }
      responses:
        201:
          description: Token request saved successfully.
          content:
            application/json:
              schema: { $ref: '#/components/schemas/ProvisionQueueResponse1' }

##-------------------------------------
## Common Model
##-------------------------------------
components:
  schemas:
    ProvisionTokenRequest1:
      x-model-version: 1.0
      description: Provision request object model
      type: object
      required:
        - provision
      properties:
        clientRequestId: { description: Request Id provided at the time of API call in the header Client-Request-Id., type: string, example: "2021-09-28T09:07:44.716+00:00" }


    ProvisionQueueResponse1:
      title: Provision resposne object model
      type: object
      required:
        - clientRequestId
        - provisionRequestId
        - cardBrand
        - createdDate
      properties:
        clientRequestId: { description: Request Id provided at the time of API call in the header Client-Request-Id., type: string, example: "2021-09-28T09:07:44.716+00:00" }
        provisionRequestId: { description: Corellation Id generated by the platform after adding request to the queue.,type: string, example: "2021-09-28T09:07:44.716+00:00" }
        createdDate: { description: Time in when the request was added into the queue., type: string,example: "2021-09-28T09:07:44.716+00:00" }
